#!/usr/bin/env bash
set -e

DICTDIR=${DICTDIR:-${PWD}}
PLIST=${PLIST:-~/info-plists}

get_7z() {
  if which 7zz &> /dev/null; then  # Official 7-Zip
    echo 7zz
  elif which 7z &> /dev/null; then  # Ancient unofficial p7zip
    echo 7z
  else
    echo "Error: 7-Zip not found." >&2
    return 127
  fi
}

get_magick() {
  if which magick &> /dev/null; then
    echo magick
  elif which convert &> /dev/null; then
    echo convert
  else
    echo "Error: ImageMagick not found." >&2
    return 127
  fi
}

get_nproc() {
  if which nproc &> /dev/null; then
    nproc
  elif which getconf &> /dev/null; then
    getconf _NPROCESSORS_ONLN
  else
    echo 1
  fi
}

if [ $# -ne 3 ] && [ $# -ne 4 ]; then
  echo "XTBook dictionary convertion helper 2407"
  echo "This script obtains a MediaWiki dump, converts it to XTBook format, and create a tarball for uploading."
  echo
  echo "Usage: $0 <source> <wiki name> <date> [split size]"
  echo "Examples: $0 wikimedia jawiki 20240101 1900M    # Japanese Wikipedia"
  echo "          $0 uncyclomedia jaunwiki 20240101 2G  # Japanese Uncyclopedia"
  echo "          $0 uncyclomedia jaunwikiimg 20240101  # Japanese Uncyclopedia Image"
  echo "          $0 fandom jabrain 20240101            # Japanese Brain Wiki"
  echo "          $0 wiki.xml somewiki 20240101         # Manually downloaded XML dump file"
  echo
  echo "Environment variables to control the behavior:"
  echo "* DICTDIR - Path to a directory where to put a resulting dictionary."
  echo "* PLIST - Path to a directory where Info.plist files are placed."
  echo "* WIKIMEDIA_MIRROR - URL of a mirror server to use for Wikimedia. Example: https://mirror.accum.se/mirror/wikimedia.org/dumps"
  echo "* MECAB_DICT - Path to a MeCab dictionary to use. Example: /var/lib/mecab/dic/ipadic"
  echo
  echo "Hints:"
  echo "* You may need to visit each dump file's distribution web site to obtain its actual name and release date."
  echo "* This script fails when your specified wiki doesn't provide its dump file or you give it wrong information."
  echo "* You may see warnings related to Info.plist since I provide only a few as preset."
  echo "  You can create it for your preferred wiki by customizing presets and adding it to the created .xtbdict folder manually."
  echo "* To convert a MediaWiki which this script doesn't support, download/extract its XML dump file manually and specify it at <source>."
  echo "* You don't need an archive to use the dictionary on XTBook, and you can cancel the process if you don't need it."
  echo "  It's basically just for me; needs to keep the OSDN repository updated."
  echo "* Check the console log when you find the converted data corrupted. You may find the reason there."
  echo "* You need *7-Zip (7zz or 7z)* for Fandom and *ImageMagick* for Uncyclopedia Image installed."
  exit
fi

mkdir -p "${DICTDIR}"
cd "${DICTDIR}"
if [ "$1" = "wikimedia" ]; then
  # Asserts that a dump exists as pipe doesn't exit with error even when it failed to download.
  if [ -n "$WIKIMEDIA_MIRROR" ]; then
    # I: Get header only, s: Suppress progress output, S: Show errors, f: Fail on error, L: Track redirect.
    curl -IsSfL "$WIKIMEDIA_MIRROR/$2/$3/$2-$3-pages-articles.xml.bz2" \
      || { curl -IsSfL "https://dumps.wikimedia.org/$2/$3/$2-$3-pages-articles.xml.bz2" && WIKIMEDIA_MIRROR=https://dumps.wikimedia.org; }
  else 
    curl -IsSfL "https://dumps.wikimedia.org/$2/$3/$2-$3-pages-articles.xml.bz2" \
      && WIKIMEDIA_MIRROR=https://dumps.wikimedia.org
  fi

  echo "Downloading and extracting an XML dump, and running MkXTBWikiplexus..."
  curl -sSfL "$WIKIMEDIA_MIRROR/$2/$3/$2-$3-pages-articles.xml.bz2" \
    | bunzip2 \
    | MkXTBWikiplexus-bin -o "$2-$3.xtbdict" -s -x1 -x2 -x3 -x4 -x5 -x6 -x7 -x8 -x9 -x11 -x12 -x13 -x14 -x15 -x110 -x111 -x117 -m \
    | MkRax-bin -o Articles.db.rax
  result=( "${PIPESTATUS[@]}" )
  test "${result[0]}" -eq 0
  test "${result[1]}" -eq 0
  test "${result[2]}" -eq 0
  mv Articles.db.rax "$2-$3.xtbdict/"

elif [ "$1" = "uncyclomedia" ]; then
  if [[ "$2" = *unwikiimg ]]; then
    MAGICK=$(get_magick)

    echo "Downloading and extracting images..."
    curl -sSfLO "https://download.uncyc.org/${2%%unwikiimg*}-images.zip"
    rm -rf "${2%%unwikiimg*}-images"
    # o: overwrite, q: quiet, j: extract all files into the same directory, d: target directory
    unzip -oqj "${2%%unwikiimg*}-images.zip" -d "${2%%unwikiimg*}-images"

    echo "Converting and resizing images..."
    mkdir -p resized
    rm -rf "resized/*"
    find "${2%%unwikiimg*}-images" -type f -print0 | xargs -P"$(get_nproc)" -0 -I{} "${MAGICK}" {} -set filename:orig '%f' -quality 85 -resize 800x480\> 'resized/%[filename:orig].jpg' || true
    test -n "$(ls resized)"

    echo "Running MkImageComplex..."
    find resized -name "*.jpg" | MkImageComplex-bin -o "$2-$3.xtbdict"
    test "${PIPESTATUS[0]}" -eq 0

    echo "Finalizing..."
    rm -rf resized "${2%%unwikiimg*}-images" "$2-$3.xtbdict/Titles.txt" "${2%%unwikiimg*}-images.zip"
    if [ -e "${PLIST}/$2.plist" ]; then
      cp "${PLIST}/$2.plist" "$2-$3.xtbdict/Info.plist"
      echo "Archiving..."
      if [ $# -eq 4 ]; then
        tar cf - "$2-$3.xtbdict" | split --numeric-suffixes=1 -a 3 -b "$4" - "$2-$3.xtbdict.tar."
        test "${PIPESTATUS[0]}" -eq 0
      else
        tar cf "$2-$3.xtbdict.tar" "$2-$3.xtbdict"
      fi
    else
      echo "WARNING: No preset Info.plist for this wiki found. You must add it yourself manually to make the created dictionary recognizable by XTBook."
      echo "WARNING: Skipping the archive creation as Info.plist is missing."
    fi
    echo "OK"
    exit

  elif [[ $2 = *unwiki ]]; then
    curl -IsSfL "https://download.uncyc.org/${2%%unwiki*}-wiki.xml.bz2"

    echo "Downloading and extracting an XML dump, and running MkXTBWikiplexus..."
    curl -sSfL "https://download.uncyc.org/${2%%unwiki*}-wiki.xml.bz2" \
      | bunzip2 \
      | MkXTBWikiplexus-bin -o "$2-$3.xtbdict" -s -x1 -x2 -x3 -x4 -x5 -x6 -x7 -x8 -x9 -x11 -x12 -x13 -x14 -x15 -x110 -x111 -x117 -m \
      | MkRax-bin -o Articles.db.rax
    result=( "${PIPESTATUS[@]}" )
    test "${result[0]}" -eq 0
    test "${result[1]}" -eq 0
    test "${result[2]}" -eq 0
    mv Articles.db.rax "$2-$3.xtbdict/"

  else
    echo "Error: Given [WikiName] isn't *unwiki or *unwikiimg."
    echo "Note: You must follow this naming rule for Uncyclopedia since it's hardcoded in this script."
    exit 1
  fi

elif [ "$1" = "fandom" ]; then
  SEVENZ=$(get_7z)

  echo "Downloading and extracting an XML dump, and running MkXTBWikiplexus..."
  curl -sSfLO "https://s3.amazonaws.com/wikia_xml_dumps/${2:0:1}/${2:0:2}/$2_pages_current.xml.7z"
  ${SEVENZ} x "$2_pages_current.xml.7z" -so \
    | MkXTBWikiplexus-bin -o "$2-$3.xtbdict" -s -x1 -x2 -x3 -x4 -x5 -x6 -x7 -x8 -x9 -x11 -x12 -x13 -x14 -x15 -x110 -x111 -x117 -m \
    | MkRax-bin -o Articles.db.rax
  result=( "${PIPESTATUS[@]}" )
  test "${result[0]}" -eq 0
  test "${result[1]}" -eq 0
  mv Articles.db.rax "$2-$3.xtbdict/"
  rm -f "$2_pages_current.xml.7z"

elif [[ $1 = *.xml ]]; then
  test -e "$1"

  echo "Running MkXTBWikiplexus..."
  MkXTBWikiplexus-bin -o "$2-$3.xtbdict" -s -x1 -x2 -x3 -x4 -x5 -x6 -x7 -x8 -x9 -x11 -x12 -x13 -x14 -x15 -x110 -x111 -x117 -m < "$1" | MkRax-bin -o Articles.db.rax
  test "${PIPESTATUS[0]}" -eq 0
  mv Articles.db.rax "$2-$3.xtbdict/"

else
  echo "Error: Source $1 is not supported."
  echo "Supported sources: wikimedia, uncyclomedia, fandom, *.xml. *.xml is your xml dump file's name."
  exit 1
fi

cd "$2-$3.xtbdict"
echo "Running YomiGenesis..."
if [ -n "$MECAB_DICT" ]; then
  YomiGenesis-bin "${MECAB_DICT}" < BaseNames.csv > Yomi.txt
else
  YomiGenesis-bin < BaseNames.csv > Yomi.txt
fi

echo "Running MkXTBIndexDB..."
MkXTBIndexDB-bin -o Search Yomi.txt

echo "Finalizing..."
rm -f Articles.db Yomi.txt BaseNames.csv Titles.csv
if [ -e "${PLIST}/$2.plist" ]; then
  cp "${PLIST}/$2.plist" Info.plist
  cd ..
  echo "Archiving..."
  if [ $# -eq 4 ]; then
    SEVENZ=$(get_7z)
    ${SEVENZ} a -v1900m "$2-$3.xtbdict.tar" "$2-$3.xtbdict"
  else
    tar cf "$2-$3.xtbdict.tar" "$2-$3.xtbdict"
  fi
else
  echo "WARNING: No preset Info.plist for this wiki found. You must add it yourself manually to make the created dictionary recognizable by XTBook."
  echo "WARNING: Skipping the archive creation as Info.plist is missing."
fi
echo "OK"
